name:                calc24
version:             0.1.0.0
github:              "megakilo/calc24"
license:             MIT
author:              "Steven Chen"
maintainer:          "megakilo@gmail.com"
copyright:           "2021 Steven Chen"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/megakilo/calc24#readme>

dependencies:
- base >= 4.7 && < 5
- random

library:
  source-dirs: src

executables:
  calc24-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -rtsopts
    dependencies:
    - calc24

tests:
  calc24-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -rtsopts
    dependencies:
    - calc24
